# Generated by Django 5.0.6 on 2026-05-26 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deposito', '0002_alter_supervisor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_medicamento',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_Riesgo',
            fields=[
                ('id_nivel_de_riesgo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=200)),
                ('fecha_vencimiento', models.DateField()),
                ('lote', models.TextField(max_length=200)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_dispensa', models.DateField()),
                ('qr', models.ImageField(blank=True, null=True, upload_to='medicamento/qr/', verbose_name='QR')),
                ('cod_barra', models.IntegerField(verbose_name=200)),
                ('refrigeracion', models.TextField(max_length=30)),
                ('cant_stock', models.IntegerField(max_length=10000000)),
                ('id_deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposito.deposito')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamento.estado_medicamento')),
                ('id_nivel_de_riesgo', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='riesgo_medicamento', to='medicamento.nivel_riesgo')),
            ],
        ),
    ]
