# Generated by Django 5.2.15 on 2026-06-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='fecha_dispensa',
            field=models.DateField(null=True),
        ),
    ]
