# Generated by Django 6.0.4 on 2026-06-10 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispensa',
            fields=[
                ('id_dispensa', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensas', to='medicamento.medicamento')),
            ],
        ),
    ]
