# Generated by Django 5.2.15 on 2026-07-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0002_alter_medicamento_fecha_dispensa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='cod_barra',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='qr',
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='fecha_dispensa',
            field=models.DateField(blank=True, null=True),
        ),
    ]
