# Generated by Django 6.0.6 on 2026-07-21 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deposito', '0001_initial'),
        ('descartable', '0001_initial'),
        ('medicamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id_remito', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
                ('id_deposito_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remitos_destino', to='deposito.deposito')),
                ('id_deposito_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remitos_origen', to='deposito.deposito')),
            ],
        ),
        migrations.CreateModel(
            name='RemitoDescartable',
            fields=[
                ('id_remito_descartable', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_descartable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remitos', to='descartable.descartable')),
                ('id_remito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_descartables', to='remito.remito')),
            ],
        ),
        migrations.CreateModel(
            name='RemitoMedicamento',
            fields=[
                ('id_remito_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remitos', to='medicamento.medicamento')),
                ('id_remito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_medicamentos', to='remito.remito')),
            ],
        ),
    ]
