# Generated by Django 6.0.6 on 2026-06-26 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id_supervisor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hueco',
            fields=[
                ('id_hueco', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('nombre_apellido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposito.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id_deposito', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('id_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposito.supervisor')),
            ],
        ),
    ]
