# Generated by Django 6.0.4 on 2026-05-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposito', '0002_alter_supervisor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
