# Generated by Django 5.2.15 on 2026-06-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposito', '0003_alter_supervisor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
