# Generated by Django 6.0.6 on 2026-06-26 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deposito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_descartable',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id_laboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_Riesgo',
            fields=[
                ('id_nivel_de_riesgo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Refrigeracion',
            fields=[
                ('refrigeracion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Descartable',
            fields=[
                ('id_descartable', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=200)),
                ('fecha_vencimiento', models.DateField()),
                ('lote', models.TextField(max_length=200)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_dispensa', models.DateField()),
                ('qr', models.ImageField(blank=True, null=True, upload_to='descartable/qr/', verbose_name='QR')),
                ('cod_barra', models.IntegerField()),
                ('cant_stock', models.IntegerField()),
                ('id_deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposito.deposito')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descartable.estado_descartable')),
                ('id_laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='descartable.laboratorio')),
                ('id_nivel_de_riesgo', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='riesgo_descartable', to='descartable.nivel_riesgo')),
                ('refrigeracion', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='descartable.refrigeracion')),
            ],
        ),
        migrations.CreateModel(
            name='Dispensa',
            fields=[
                ('id_dispensa', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_descartable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensas', to='descartable.descartable')),
            ],
        ),
    ]
