# Generated by Django 5.2.15 on 2026-07-22 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descartable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descartable',
            name='cod_barra',
        ),
        migrations.RemoveField(
            model_name='descartable',
            name='qr',
        ),
    ]
